name: Dart Checks
on:
  pull_request:
  push: 
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Recursive pub get
        run: find . -name 'pubspec.yaml' -execdir dart pub get \;
    
      - name: Check formatting
        run: dart format --set-exit-if-changed .
    
      - name: Run Analyzer
        run: dart analyze .
    
      - name: Run Tests with Coverage
        run: dart pub run coverage:test_with_coverage

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
